name: Build No-Steam-Info Plugin

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          python3 \
          python3-pip \
          python3-setuptools \
          cmake \
          libssl-dev \
          zlib1g-dev \
          git \
          wget
          
    - name: Install AMBuild from source
      run: |
        git clone https://github.com/alliedmodders/ambuild.git
        cd ambuild
        pip3 install --user .
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      
    - name: Clone SourceMod SDK
      run: |
        git clone https://github.com/alliedmodders/sourcemod.git ~/sourcemod
        cd ~/sourcemod
        git checkout 1.11-dev  # Используем конкретную версию
        
    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        python3 ../configure.py --sdksourcemod=$HOME/sourcemod
        ambuild
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: no-steam-info-plugin
        path: build/
        retention-days: 30
