name: Build No Steam Info Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install ambuild
        # Скачай HL2SDK, MMS, SM вручную или через скрипт (пример ниже)
        wget https://github.com/alliedmodders/hl2sdk/archive/refs/heads/csgo.zip -O hl2sdk.zip
        unzip hl2sdk.zip -d hl2sdk
        wget https://mms.alliedmods.net/mmsdrop/1.11/mmsource-1.11.0-git1148-linux.tar.gz
        tar -xzf mmsource-1.11.0-git1148-linux.tar.gz -C mms
        wget https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git6916-linux.tar.gz
        tar -xzf sourcemod-1.11.0-git6916-linux.tar.gz -C sm

    - name: Configure
      run: python configure.py --hl2sdk-root=hl2sdk/hl2sdk-csgo --mms-path=mms/metamod --sm-path=sm/sourcemod --enable-optimize

    - name: Build
      run: ambuild

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: extension-build
        path: build/**
