name: Build No-Steam-Info Plugin

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          python3 \
          python3-pip \
          cmake \
          libssl-dev \
          zlib1g-dev \
          git \
          wget
          
    - name: Install AMBuild
      run: pip3 install ambuild
      
    - name: Clone SourceMod SDK
      run: |
        git clone https://github.com/alliedmodders/sourcemod.git ~/sourcemod
        cd ~/sourcemod
        git checkout --detach  # Используем стабильную версию
        
    - name: Configure build
      run: |
        mkdir -p build
        cd build
        python3 ../configure.py --sdksourcemod=$HOME/sourcemod
        echo "Configuration completed"
        
    - name: Build project
      run: |
        cd build
        ambuild
        echo "Build completed successfully"
        
    - name: List built files
      run: |
        find build -name "*.so" -o -name "*.dll" -o -name "*.ext" | head -20
        ls -la build/package/ 2>/dev/null || echo "No package directory"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: no-steam-info-build
        path: |
          build/package/
          build/*.so
          build/*.ext
        retention-days: 30
