name: Build No-Steam-Info Direct

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ gcc make cmake \
          libssl-dev zlib1g-dev git wget
          
    - name: Get SourceMod SDK
      run: |
        git clone https://github.com/alliedmodders/sourcemod.git ~/sourcemod
        cd ~/sourcemod
        git checkout 1.11-dev
        
    - name: Download required headers
      run: |
        cd ~/sourcemod/public
        wget -q https://raw.githubusercontent.com/alliedmodders/sourcemod/master/public/amtl/amtl.h || true
        
    - name: Manual compilation
      run: |
        # Копируем необходимые заголовочные файлы
        cp ~/sourcemod/public/smsdk_ext.h . || true
        cp ~/sourcemod/public/IExtensionSys.h . || true
        cp ~/sourcemod/public/ISourceMod.h . || true
        
        # Компилируем вручную
        g++ -c -fPIC -I. -I~/sourcemod/public -I~/sourcemod/core \
          extension.cpp -o extension.o
        
        # Создаем shared library
        g++ -shared -o no_steam_info.so extension.o -lssl -lcrypto
        
        # Проверяем результат
        file no_steam_info.so || echo "Binary file not created"
        ls -la *.so || echo "No .so files found"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: manual-build
        path: |
          *.so
          *.o
